import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount, useReadContract } from "wagmi";
import TransferForm from "@/components/TransferForm";
import { parseUnits } from "../utils";
import { useConfig } from "@/hooks/useConfig";

const Home: NextPage = () => {
  const { address } = useAccount();
  const config = useConfig();

  const { data: balance } = useReadContract({
    ...config,
    functionName: "balanceOf",
    args: [address],
  });
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main>
        <ConnectButton />
        <div className="">address:{address}</div>
        <div>
          {typeof balance === "bigint" && parseUnits(balance.toString(), 18)}
        </div>
        <TransferForm />
      </main>
    </div>
  );
};

export default Home;
