import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount, useReadContract } from "wagmi";
import { parseUnits } from "../utils";
import MyErc20 from "../contracts/MyERC20.json";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { address } = useAccount();

  const { data: balance } = useReadContract({
    address: MyErc20.address as `0x${string}`,
    abi: MyErc20.abi,
    functionName: "balanceOf",
    args: [address],
  });
  console.log("🚀 ~ data:", balance);
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <div className="">address:{address}</div>
        <div>{balance && <>{parseUnits(balance, 35)}</>}</div>
      </main>
    </div>
  );
};

export default Home;
